#!/bin/bash

# Check if necessary programs are installed
for prog in jq; do
	[ ! "$(which "$prog")" ] && echo "Please install $prog!" && exit 1
done
# If notify-send is not installed, use echo as notifier
[ ! "$(which notify-send)" ] && notifier="echo" || notifier="notify-send"

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
# Default config directory
configdir="$SCRIPTPATH/.config"

if  [[ $# -ne 0 ]] && [[ $1 == "clean" ]] ; then
	rm -rf $SCRIPTPATH/downloads/* 2>/dev/null 
	echo "Cleaning complete."
	exit 0;
fi

defaultsub="linuxmemes"

# If no argument is passed
if [ -z "$1" ]; then
	# Ask the user to enter a subreddit
	subreddit=$defaultsub

# Otherwise assign the first argument to the
# subreddit variable
else
	subreddit="$1"
fi

# Default directory used to store the feed file and fetched images
cachedir="$SCRIPTPATH/downloads/$subreddit"
rm "${cachedir:?}"/*  2>/dev/null 
mkdir -p "$cachedir"

# Limit the maximum number of requests to make
limit=$2
if [ -z "$2" ]; then
	limit=20
fi

# Download the subreddit feed, containing only the
# first n entries (limit), and store it inside
# cachedir/tmp.json
curl -H "User-agent: 'your bot 0.1'" "https://www.reddit.com/r/$subreddit/hot.json?limit=$limit" > "$cachedir/tmp.json"

# Create a list of images
imgs=$(jq '.' < "$cachedir/tmp.json" | grep url_overridden_by_dest | grep -Eo "http(s|)://.*(jpg|png)\b" | sort -u)

# If there are no images, exit
[ -z "$imgs" ] && $notifier "Redyt" "sadly, there are no images for subreddit $subreddit, please try again later!" && exit 1


# Send a notification
printf "\n\nDownloading....		limit is $limit posts (both image and non-image posts)"
$notifier "Redyt" "📩 Downloading your 🖼️ Images"

# Download images to $cachedir
wget -P "$cachedir" $imgs 2>/dev/null

# Send a notification
$notifier  "Redyt" "👍 Download Finished, Enjoy! 😊"

# Once finished, remove all of the cached images 
xdg-open $cachedir   2>/dev/null 

#Cleanup
rm $cachedir/tmp.json 2>/dev/null 
rm tmp.json 2>/dev/null 
rm *.out 2>/dev/null  
